# Assignment No 1b
###### *Hassan Raza*
----
## Goal

Your goal in this assigment is to implement and refresh the multivariate concepts learned during the previous weeks using the Python language. This will not only solidify your Python understanding but also give you strong footing for further advancement :)

**Note** Please note that can use *numpy and scipy* to complete the tasks. In case you need any help you can post on google classroom.

## Submission Instructions
You are required to submit the original notebook file on the google classroom (with .ipynb extension), with complete set of outputs. Students failing to do so will get zero marks. 

*Please read each step carefully and understand it fully before proceeding with code writing*

## Plagiarism
Any form of plagiarism will not be tolerated and result in 0 marks.

**So Lets Start**

In [1]:
# magic command to include all the necessary libraries
%pylab inline 

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [ ]:
#Download the IRIS dataset
#"!" means run the bash (shell) command
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

In [3]:
#import pandas and name this namespace as pd
import pandas as pd

In [4]:
#Load data and name the columns
data=pd.read_csv('iris.data.txt')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
print (data.describe())

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   149.000000  149.000000   149.000000  149.000000
mean      5.848322    3.051007     3.774497    1.205369
std       0.828594    0.433499     1.759651    0.761292
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.400000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


In [5]:
#Code for generating data....
datalist=[] #create an empty list
# data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
datalist.append(list(data['PetalLength'].dropna()))
datalist.append(list(data['PetalWidth'].dropna()))
datalist.append(list(data['SepalLength'].dropna()))
datalist.append(list(data['SepalWidth'].dropna()))

#If you want you build a numpy array from this list.

print ("PetalLength=", datalist[0])
print ("PetalWidth=", datalist[1])

#This and above code are both same...
# datalist=[0]*2#create a list of 2 elements
# datalist[0]=(list(data['PetalLength'].dropna()))
# datalist[1]=(list(data['PetalWidth'].dropna()))
#data list is a list of two elements, where index=0 contains data corresponding to petal 
# length and index=1 contains data corresponding to petal width
# print("PetalLength=", datalist[0])
# print("PetalWidth=", datalist[1])

PetalLength= [1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1.0, 1.7, 1.9, 1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5, 4.9, 4.0, 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4.0, 4.7, 3.6, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4.0, 4.9, 4.7, 4.3, 4.4, 4.8, 5.0, 4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4.0, 4.4, 4.6, 4.0, 3.3, 4.2, 4.2, 4.2, 4.3, 3.0, 4.1, 6.0, 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5.0, 5.1, 5.3, 5.5, 6.7, 6.9, 5.0, 5.7, 4.9, 6.7, 4.9, 5.7, 6.0, 4.8, 4.9, 5.6, 5.8, 6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1, 5.9, 5.7, 5.2, 5.0, 5.2, 5.4, 5.1]
PetalWidth= [0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2, 0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2

*In all the tasks given below use the list variable `datalist` (defined above) to answer all the questions.*

#### Task1
----------------
Lets model the petal length and width as continuous random variable $X=(x_1,x_2)$. Find the mean of this random variable. Here $x_1$ specifies the petal length and $x_2$ its width.

In [8]:
def calculate_mean(data):
    sum_of_val=0

    for i in data:
        sum_of_val+=i

    mean_of_val= sum_of_val/len(data)
    return mean_of_val

mean_petal_length = calculate_mean(datalist[0])
mean_petal_length = calculate_mean(datalist[1])

print(f"The mean of petal length is {mean_petal_length}")
print(f"The mean of petal width is {mean_petal_length}")


The mean of petal length is 3.7744966442953043
The mean of petal width is 1.2053691275167793


#### Task2
----------------
Compute the covariance matrix $X$ using outper product formula, i.e. $\Sigma=\frac{1}{n}Z^T\;Z$, where $Z$ is centered data matrix (mean = 0)

In [11]:
def center_data(data, mean):
    result = []

    for x in data:
        difference = x - mean
        result.append(difference)
        
    return result

In [13]:
def compute_covariance(Z):
    
    Z = np.array(Z)
    
    n = Z.shape[0]
    Z_T = Z.T
    covariance_matrix = np.dot(Z_T, Z) / n
    
    return covariance_matrix

In [20]:
centered_pl = center_data(datalist[0], mean_petal_length)
centered_pw = center_data(datalist[1], mean_petal_width)

array = []
for i in range(len(centered_pl)):
    newlist = [centered_pl[i], centered_pw[i]]
    array.append(newlist)

covariance = compute_covariance(array)

print("Covariance Matrix:")
print(covariance)


Covariance Matrix:
[[3.07559119 1.2804725 ]
 [1.2804725  0.57567587]]


#### Task3: Multivariate Gaussian
----------------
Let's model $X$ with multivariate Gaussian. Find the probability of having flowers with petal width and height in the following range $P(3.5 < x_1 < 3.7,5.5 < x_2 <5.6)$.
Recall that 
$$f_{\mathbf x}(x_1,\ldots,x_k) = \frac{1}{\sqrt{(2\pi)^k|\boldsymbol\Sigma|}} \exp\left(-\frac{1}{2}({\mathbf x}-{\boldsymbol\mu})^\mathrm{T}{\boldsymbol\Sigma}^{-1}({\mathbf x}-{\boldsymbol\mu}) \right)$$

where ${\mathbf x}$ is a real k-dimensional column vector and $|\boldsymbol\Sigma|$ is the determinant of $\boldsymbol\Sigma$. For our this case $k=2$ 

In [16]:
def determinant(matrix):
    return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

In [17]:
def inverse(matrix):
    det = determinant(matrix)
    return [[matrix[1][1] / det, -matrix[0][1] / det],
            [-matrix[1][0] / det, matrix[0][0] / det]]

In [18]:
def pdf(x, mu, sigma):
    k = len(mu)
    diff = [x[i] - mu[i] for i in range(k)]
    inv_sigma = inverse(sigma)
    exponent = -0.5 * sum(diff[i] * sum(inv_sigma[i][j] * diff[j] for j in range(k)) for i in range(k))
    coeff = 1 / (math.sqrt((2 * math.pi) ** k * determinant(sigma)))
    return coeff * math.exp(exponent)

In [ ]:
mean_val=[mean_petal_length,mean_petal_length]

lower_bound=[3.5,5.5]
upper_bound=[3.7,5.6]

num_steps=100
dx1=(upper_bound[0]-lower_bound[0])/num_steps
dx2=(upper_bound[1]-lower_bound[1])/num_steps
probability=0.0

for i in range(len(datalist[0])):
    for j in range(len(datalist[0])):
        x1=lower_bound[0]+(i+0.5)*dx1
        x2=lower_bound[1]+(j+0.5)*dx2
        
        probability+=pdf([x1,x2],mean_val,covariance)*dx1*dx2


#### Task4: Multivariate Gaussian

Now consider that both the attributes are statistically independent and normally distributed then what will be the probability of $P(3.5 < x_1 < 3.7,5.5 < x_2 <5.6)$


In [28]:
def probability(val1, val2, mean, sigma):
    newval1 = (val1-mean)/sigma
    newval2= (val2-mean)/sigma
    return newval2 -newval1

In [34]:
import numpy as np

sigma1= np.cov(datalist[0])
sigma2= np.cov(datalist[1])

prob_x1 = probability(3.5, 3.7, mean_of_petal_length, sigma1)
prob_x2 = probability(5.5, 5.6, mean_of_petal_width, sigma2)

#x1 and x2 are independent, multiply the two probabilities
joint_probability = prob_x1 * prob_x2

print(f"Joint probability:{joint_probability}")

Joint probability:0.011144850706766051


#### Task5: Categorical Random Variables.
----------------
Lets categorize the petal length variable to four categories, i.e very short $\in[1,1.6]$, short $\in(1.6,4.4]$, long $\in(4.4,5.1]$, very long $\in(5.1,6.9]$ and model this varible using random variable $x$

Find the probability of this cateogrical random variable.

In [45]:
def categorize_petal_length(petal_length):
    if 1<=petal_length<=1.6:
        return 'Very Short'
    elif 1.6<petal_length<=4.4:
        return 'Short'
    elif 4.4<petal_length<=5.1:
        return 'Long'
    elif 5.1<petal_length<=6.9:
        return 'Very Long'
    else:
        return 'Unknown'

In [48]:
categories={'Very Short':0,'Short':0,'Long':0,'Very Long':0}
dict_of_categories={'Very Short':[],'Short':[],'Long':[],'Very Long':[]}
total_count=len(PetalLength)

for length in datalist[0]:
    category=categorize_petal_length(length)
    categories[category]+=1
    dict_of_categories[category].append(length)

for category,count in categories.items():
    probability=count/total_count
    print(f"Probability of {category}: {probability}")

Probability of Very Short: 0.28859060402684567
Probability of Short: 0.2348993288590604
Probability of Long: 0.2483221476510067
Probability of Very Long: 0.22818791946308725


#### Task6: Categorical Random Variables.
Find the mean and covariance matrix of categorical variable $x$.

In [70]:
newlist=[]
for category,list_of_categ in dict_of_categories.items():
    meanval=sum(list_of_categ)/len(datalist[0])
    newlist.append(list_of_categ)
    
    print(f"Mean of {category}: {meanval}")

Mean of Very Short: 0.41073825503355704
Mean of Short: 0.8409395973154361
Mean of Long: 1.1932885906040267
Mean of Very Long: 1.3295302013422818


In [57]:
lengthlist=[]
for category,list_of_categ in dict_of_categories.items():
    print(f"{category}: {list_of_categ}")
    lengthlist.append(len(list_of_categ))

Very Short: [1.4, 1.3, 1.5, 1.4, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.5, 1.5, 1.0, 1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6, 1.4, 1.6, 1.4, 1.5, 1.4]
Short: [1.7, 1.7, 1.7, 1.7, 1.9, 1.9, 4.0, 3.3, 3.9, 3.5, 4.2, 4.0, 3.6, 4.4, 4.1, 3.9, 4.0, 4.3, 4.4, 3.5, 3.8, 3.7, 3.9, 4.4, 4.1, 4.0, 4.4, 4.0, 3.3, 4.2, 4.2, 4.2, 4.3, 3.0, 4.1]
Long: [4.7, 4.5, 4.9, 4.6, 4.5, 4.7, 4.6, 4.7, 4.5, 4.5, 4.8, 4.9, 4.7, 4.8, 5.0, 4.5, 5.1, 4.5, 4.5, 4.7, 4.6, 5.1, 4.5, 5.1, 5.0, 5.1, 5.0, 4.9, 4.9, 4.8, 4.9, 5.1, 4.8, 5.1, 5.1, 5.0, 5.1]
Very Long: [6.0, 5.9, 5.6, 5.8, 6.6, 6.3, 5.8, 6.1, 5.3, 5.5, 5.3, 5.5, 6.7, 6.9, 5.7, 6.7, 5.7, 6.0, 5.6, 5.8, 6.1, 6.4, 5.6, 5.6, 6.1, 5.6, 5.5, 5.4, 5.6, 5.9, 5.7, 5.2, 5.2, 5.4]


#### Task7: Categorical Random Variables.

If we select 10 random flowers what will be the probability of picking 3 very short length, 2 short length, 4 long length and 1 very long petal length flowers.

Multinomial coefficient: n! / (k1! k2! k3! k4!)


In [ ]:
def calculate_probability(count, total):
    return count / total

In [58]:
import math

p_very_short=lengthlist[0]/len(datalist[0])
p_short=lengthlist[1]/len(datalist[0])
p_long=lengthlist[2]/len(datalist[0])
p_very_long=lengthlist[3]/len(datalist[0])

k_very_short=3
k_short=2
k_long=4
k_very_long=1

n=10

multinomial_coeff=math.factorial(n)/(math.factorial(k_very_short)*math.factorial(k_short)*math.factorial(k_long)*math.factorial(k_very_long))

probability=multinomial_coeff*(p_very_short**k_very_short)*(p_short**k_short)*(p_long**k_long)*(p_very_long**k_very_long)

print("Probability of selecting the specified combination of flowers:",probability)

Probability of selecting the specified combination of flowers: 0.014498902511786727


#### Task8: Bivariate Categorical Random Variables.
----------------
Lets also categorize the petal width variable to three categories, i.e short $\in[0.1,1.0]$, medium  $\in(1.0,1.75)$, long $\in(1.75,2.5]$.

Now lets model both the petal length and width as bivariate categorical random variable $X$.
Find the probability for following cases.

$$p(x_1=[1000], x_2=[000])$$
$$p(x_1=[1000], x_2=[001])$$

$$p(x_1=[0010], x_2=[010])$$
$$p(x_1=[0001], x_2=[100])$$


In [71]:
def categorize_petal_width(width):
    if 0.1<=width<=1.0:
        return 'Short'
    elif 1.0<width<=1.75:
        return 'Medium'
    elif 1.75<width<=2.5:
        return 'Long'
    return None

In [72]:
def count_categories(lengths,widths):
    length_categories=[]
    width_categories=[]

    for length in lengths:
        length_categories.append(categorize_petal_length(length))

    for width in widths:
        width_categories.append(categorize_petal_width(width))

    combined_counts={}

    for i in range(len(length_categories)):
        category_pair=(length_categories[i],width_categories[i])
        if category_pair in combined_counts:
            combined_counts[category_pair]+=1
        else:
            combined_counts[category_pair]=1

    return combined_counts

In [73]:
combined_counts = count_categories(datalist[0], datalist[1])
combined_counts

{('Very Short', 'Short'): 43,
 ('Short', 'Short'): 13,
 ('Long', 'Medium'): 23,
 ('Short', 'Medium'): 22,
 ('Long', 'Long'): 14,
 ('Very Long', 'Long'): 32,
 ('Very Long', 'Medium'): 2}

#### Task9: Normalization
----------------
Normalize both the attributes (petal length and petal width) such that after normalization their values must lie in the interval [-2, 5]

In [75]:
def normalize(data,minval=-2,maxval=5):
    old_min=min(data)
    old_max=max(data)
    
    normalized_data = []
    
    for x in data:
        normalized_value = minval + (x - old_min) * (maxval - minval) / (old_max - old_min)
        normalized_data.append(normalized_value)

    return normalized_data

In [76]:
normalized_length = normalize(datalist[0])
normalized_width = normalize(datalist[1])

print("Normalized Petal Length:", normalized_length)
print("Normalized Petal Width:", normalized_width)


Normalized Petal Length: [-1.5254237288135595, -1.6440677966101696, -1.4067796610169492, -1.5254237288135595, -1.1694915254237288, -1.5254237288135595, -1.4067796610169492, -1.5254237288135595, -1.4067796610169492, -1.4067796610169492, -1.2881355932203389, -1.5254237288135595, -1.8813559322033897, -1.7627118644067798, -1.4067796610169492, -1.6440677966101696, -1.5254237288135595, -1.1694915254237288, -1.4067796610169492, -1.1694915254237288, -1.4067796610169492, -2.0, -1.1694915254237288, -0.9322033898305087, -1.2881355932203389, -1.2881355932203389, -1.4067796610169492, -1.5254237288135595, -1.2881355932203389, -1.2881355932203389, -1.4067796610169492, -1.4067796610169492, -1.5254237288135595, -1.4067796610169492, -1.7627118644067798, -1.6440677966101696, -1.4067796610169492, -1.6440677966101696, -1.4067796610169492, -1.6440677966101696, -1.6440677966101696, -1.6440677966101696, -1.2881355932203389, -0.9322033898305087, -1.5254237288135595, -1.2881355932203389, -1.5254237288135595, -1

#### Task10: Class wise mean vector and covariance matrix...
Iris dataset have three different classes, now go and compute the class-wise (setosa, versicolor and virginica) mean vector and covariance matrix.

In [82]:
data

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [86]:
import pandas as pd
import numpy as np

data=pd.read_csv('iris.data.txt')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Species']

setosa=data[data['Species']=='Iris-setosa'].iloc[:,:-1]
versicolor=data[data['Species']=='Iris-versicolor'].iloc[:,:-1]
virginica=data[data['Species']=='Iris-virginica'].iloc[:,:-1]

mean_setosa=setosa.mean().values
mean_versicolor=versicolor.mean().values
mean_virginica=virginica.mean().values

cov_setosa=setosa.cov().values
cov_versicolor=versicolor.cov().values
cov_virginica=virginica.cov().values

print("Mean Vector for Setosa:",mean_setosa)
print("Covariance Matrix for Setosa:\n",cov_setosa)
print("\nMean Vector for Versicolor:",mean_versicolor)
print("Covariance Matrix for Versicolor:\n",cov_versicolor)
print("\nMean Vector for Virginica:",mean_virginica)
print("Covariance Matrix for Virginica:\n",cov_virginica)

Mean Vector for Setosa: [5.00408163 3.41632653 1.46530612 0.24489796]
Covariance Matrix for Setosa:
 [[0.12664966 0.10222364 0.01660289 0.01085459]
 [0.10222364 0.14806122 0.01203656 0.0117517 ]
 [0.01660289 0.01203656 0.03064626 0.0057568 ]
 [0.01085459 0.0117517  0.0057568  0.01169218]]

Mean Vector for Versicolor: [5.936 2.77  4.26  1.326]
Covariance Matrix for Versicolor:
 [[0.26643265 0.08518367 0.18289796 0.05577959]
 [0.08518367 0.09846939 0.08265306 0.04120408]
 [0.18289796 0.08265306 0.22081633 0.07310204]
 [0.05577959 0.04120408 0.07310204 0.03910612]]

Mean Vector for Virginica: [6.588 2.974 5.552 2.026]
Covariance Matrix for Virginica:
 [[0.40434286 0.09376327 0.3032898  0.04909388]
 [0.09376327 0.10400408 0.07137959 0.04762857]
 [0.3032898  0.07137959 0.30458776 0.04882449]
 [0.04909388 0.04762857 0.04882449 0.07543265]]


#### Task11: Caclulating the Probability of a flower belonging to a particular class
Using above information, lets model each class to be modeled by continuous multivariate Gaussian Random varible. Now we have recorded a flower with following attributes (sepal lenght=4, petal length=6, sepal width=4, sepal length=5.5) in the field, which class it belongs. 

In [95]:
def multivariate_gaussian_pdf(x,mean,cov):
    k=len(mean)
    diff=np.array(x)-np.array(mean)
    cov_inv=inv(cov)
    exponent=-0.5*diff.T.dot(cov_inv).dot(diff)
    return (1/sqrt((2*pi)**k*det(cov)))*exp(exponent)

In [94]:
import numpy as np
from numpy.linalg import inv,det
from math import sqrt,pi,exp

# Flower attributes
x=[4,6,4,5.5]

# Calculate probabilities
p_setosa=multivariate_gaussian_pdf(x,mean_setosa,cov_setosa)
p_versicolor=multivariate_gaussian_pdf(x,mean_versicolor,cov_versicolor)
p_virginica=multivariate_gaussian_pdf(x,mean_virginica,cov_virginica)

print(f"Probability of belonging to Setosa:{p_setosa}")
print(f"Probability of belonging to Versicolor:{p_versicolor}")
print(f"Probability of belonging to Virginica:{p_virginica}")

# Determine the most likely class
probabilities={'Setosa':p_setosa,'Versicolor':p_versicolor,'Virginica':p_virginica}
most_likely_class=max(probabilities,key=probabilities.get)
print(f"The flower most likely belongs to:{most_likely_class}")

Probability of belonging to Setosa: 0.000000
Probability of belonging to Versicolor: 0.000000
Probability of belonging to Virginica: 0.000000
The flower most likely belongs to: Virginica



#### Task12:  X is a normally distributed variable with mean μ = 30 and standard deviation σ = 4. Find 

a) P(x < 40)

b) P(x > 21)

c) P(30 < x < 35)

You can use scipy.stats.norm functions to answer these questions. These problems are contributed by an anonymous source.

In [97]:
import scipy.stats as s

mean=30
std_dev=4

# a)
p1=s.norm.cdf(40,mean,std_dev)
print(f"P(x < 40) = {p1}")

# b)
p2=1-s.norm.cdf(21,mean,std_dev)
print(f"P(x > 21) = {p2}")

# c)
p3=s.norm.cdf(35,mean,std_dev)-s.norm.cdf(30,mean,std_dev)
print(f"P(30 < x < 35) = {p3}")

P(x < 40) = 0.9937903346742238
P(x > 21) = 0.9877755273449553
P(30 < x < 35) = 0.39435022633314465


#### Task13: 
The time taken to assemble a car in a certain plant is a random variable having a normal distribution with a mean of 20 hours and a standard deviation of 2 hours. What is the probability that a car can be assembled at this plant in:

a) less than 19.5 hours?

b) between 20 and 22 hours?

In [92]:
import scipy.stats as stats

mean=20
std_dev=2

# a)
prob_less_than_19_5=stats.norm.cdf(19.5,loc=mean,scale=std_dev)
print("Probability of assembling a car in less than 19.5 hours:",prob_less_than_19_5)

# b)
prob_between_20_and_22=stats.norm.cdf(22,loc=mean,scale=std_dev)-stats.norm.cdf(20,loc=mean,scale=std_dev)
print("Probability of assembling a car between 20 and 22 hours:",prob_between_20_and_22)

Probability of assembling a car in less than 19.5 hours: 0.4012936743170763
Probability of assembling a car between 20 and 22 hours: 0.3413447460685429


In [90]:
from scipy.stats import norm

meanval=20
sigma=2

# Probability of less than 19.5 hours
z_19_5 = (19.5 - mu) / sigma
p_less_than_19_5 = norm.cdf(z_19_5)

# Probability of between 20 and 22 hours
z_20 = (20 - mu) / sigma
z_22 = (22 - mu) / sigma
p_less_than_22 = norm.cdf(z_22)
p_less_than_20 = norm.cdf(z_20)
p_between_20_and_22 = p_less_than_22 - p_less_than_20

print(f"Probability of assembling in less than 19.5 hours: {p_less_than_19_5:.4f}")
print(f"Probability of assembling between 20 and 22 hours: {p_between_20_and_22:.4f}")


Probability of assembling in less than 19.5 hours: 1.0000
Probability of assembling between 20 and 22 hours: 0.0000


#### Task14:
A manufacturer of metal pistons finds that on average, 12% of his pistons are rejected because they are either oversized or undersized. What is the probability that a batch of 10 pistons will contain

(a) no more than 2 rejects?

(b) at least 2 rejects?

In [87]:
# Binomial coefficient
def binomial_coefficient(n, k):
    return math.comb(n, k)

In [88]:
def binomial_pmf(n,k,p):
    return binomial_coefficient(n,k)*(p**k)*((1-p)**(n-k))

In [89]:
import math

n = 10
p = 0.12

# Probability of no more than 2 rejects
P_0 = binomial_pmf(n, 0, p)
P_1 = binomial_pmf(n, 1, p)
P_2 = binomial_pmf(n, 2, p)

Q1 = P_0 + P_1 + P_2

# Probability of at least 2 rejects
P_less_than_2 = P_0 + P_1
Q2 = 1 - P_less_than_2

print(f"Probability of no more than 2 rejects: {Q1}")
print(f"Probability of at least 2 rejects: {Q2}")


Probability of no more than 2 rejects: 0.8913182062780246
Probability of at least 2 rejects: 0.34172496579595857
